[build]
  command = "rm -rf themes/* && git clone https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke && echo -e 'baseURL = \"/\"\ntitle = \"Ravi Pappu\"\ntheme = \"ananke\"' > config.toml && hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.111.3"
