[build]
  command = "rm -f content/_index.md && cp themes/academic/exampleSite/content/home/about.md content/home/about.md && cp themes/academic/exampleSite/content/home/hero.md content/home/ && rm -rf content/publication && hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"