[build]
  command = "rm -rf themes/academic themes/wowchemy && git clone https://github.com/gcushen/hugo-academic.git themes/academic && ls -la themes/academic/ && find themes/academic -name 'config*' -o -name 'example*' | head -10"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.68.3"
