[build]
  command = "rm -rf themes/academic themes/wowchemy && git clone https://github.com/gcushen/hugo-academic.git themes/academic && cp themes/academic/exampleSite/config.toml config.toml && rm -rf content && cp -r themes/academic/exampleSite/content . && hugo && ls -la public/ | head -10"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.68.3"