[build]
  command = "ls -la themes/academic/exampleSite/content/ && ls -la themes/academic/exampleSite/content/home/ && rm -rf content/publication && hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"