[build]
  command = "rm -rf themes/wowchemy && git clone https://github.com/gcushen/hugo-academic.git themes/academic && hugo && ls -la public/ && cat public/index.html | head -10"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.68.3"